channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=he0c23c2_0
  - av=10.0.0=py310hef11e44_4
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - dav1d=1.2.1=hcfcfb64_0
  - ffmpeg=6.1.2=gpl_h63b3451_706
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.4.5=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.84.4=hfaec014_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - mkl=2024.2.2=h57928b3_16
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.4=h725018a_0
  - pcre2=10.46=h3402e2f_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - python=3.10.13=he1021f5_0
  - python_abi=3.10=2_cp310
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - svt-av1=2.3.0=he0c23c2_0
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - accelerate==0.24.1
      - aiofiles==23.2.1
      - aiohttp==3.8.6
      - aiosignal==1.4.0
      - alembic==1.17.0
      - allosaurus==1.0.2
      - altair==5.5.0
      - antlr4-python3-runtime==4.8
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==25.4.0
      - audioread==3.0.1
      - babel==2.17.0
      - beautifulsoup4==4.12.2
      - bitarray==3.7.2
      - bleach==6.1.0
      - cachetools==6.2.1
      - certifi==2023.7.22
      - cffi==2.0.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clldutils==3.20.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.7.0
      - comm==0.2.3
      - contourpy==1.3.2
      - csvw==3.1.3
      - ctranslate2==3.21.0
      - cycler==0.12.1
      - cython==3.1.6
      - datasets==2.14.6
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - distance==0.1.3
      - docker-pycreds==0.4.0
      - editdistance==0.6.2
      - einops==0.7.0
      - encodec==0.1.1
      - eng-to-ipa==0.0.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fairseq==0.12.2
      - fastapi==0.104.1
      - faster-whisper==0.9.0
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - ffmpy==0.6.4
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - future==0.18.3
      - g2p-en==2.1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.2
      - gradio==3.41.2
      - gradio-client==0.5.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.14.0
      - httpcore==1.0.1
      - httpx==0.25.1
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - hydra-core==1.0.7
      - hyperpyyaml==1.2.2
      - idna==3.4
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.1
      - isodate==0.7.2
      - isoduration==20.11.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.2
      - jiwer==3.0.3
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - julius==0.2.7
      - jupyter==1.0.0
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - langid==1.1.6
      - language-tags==1.2.0
      - lark==1.3.1
      - lazy-loader==0.4
      - librosa==0.10.1
      - lightning-utilities==0.15.2
      - llvmlite==0.41.1
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.15
      - munkres==1.1.4
      - narwhals==2.10.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - notebook==7.0.6
      - notebook-shim==0.2.4
      - numba==0.58.1
      - numpy==1.26.0
      - oauthlib==3.3.1
      - omegaconf==2.0.6
      - onnxruntime==1.16.2
      - onnxruntime-gpu==1.16.2
      - openai-whisper==20230306
      - optuna==3.4.0
      - orjson==3.11.4
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.1.2
      - pandocfilters==1.5.1
      - panphon==0.20.0
      - parso==0.8.5
      - phonemizer==2.2.1
      - pillow==10.1.0
      - pip==23.3
      - platformdirs==4.5.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - praatio==6.1.0
      - primepy==1.3
      - progressbar==2.5
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==3.20.3
      - psutil==7.1.2
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydub==0.25.1
      - pygments==2.19.2
      - pylatexenc==2.10
      - pyparsing==3.2.5
      - pyreadline3==3.5.4
      - pysle==4.0.1
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.1.1
      - pytorch-metric-learning==2.9.0
      - pytz==2025.2
      - pywin32==311
      - pywinpty==3.0.2
      - pyyaml==6.0.1
      - pyzmq==27.1.0
      - qtconsole==5.5.1
      - qtpy==2.4.3
      - rapidfuzz==3.5.2
      - rdflib==7.3.0
      - referencing==0.37.0
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986==1.5.0
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.6.0
      - rotary-embedding-torch==0.8.9
      - rpds-py==0.28.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - segments==2.2.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.4.6
      - soundfile==0.12.1
      - soupsieve==2.8
      - soxr==0.3.7
      - speechbrain==0.5.15
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - starlette==0.27.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tomli==2.3.0
      - torch==2.1.0
      - torch-audiomentations==0.11.0
      - torch-pitch-shift==1.2.5
      - torchaudio==2.1.0
      - torchcrepe==0.0.24
      - torchmetrics==1.2.0
      - torchvision==0.16.0
      - tornado==6.5.2
      - tortoise-tts==3.0.0
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.31.0
      - typeguard==4.4.4
      - tzdata==2025.2
      - unicodecsv==0.14.1
      - unidecode==1.4.0
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - urllib3==2.0.7
      - uvicorn==0.24.0.post1
      - vocos==0.1.0
      - wandb==0.16.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - websockets==11.0.3
      - werkzeug==3.0.1
      - wget==3.2
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yarl==1.22.0